[package]
name = "lilit"
version = "0.1.0"
authors = ["tanin"]

[dependencies]
regex = "0.2.0"
serde_json = "1.0"
inkwell = { git = "https://github.com/tanin47/inkwell", rev = "46d576c63a7bec3a5ff4c81efbe74842f850ff0a", features = ["llvm6-0"] }
