[package]
name = "lilit"
version = "0.1.0"
authors = ["tanin"]

[dependencies]
regex = "1.4.2"
serde_json = "1.0.59"
inkwell = { git = "https://github.com/TheDan64/inkwell", rev = "79070d9fbb0e7ed1c96c7133273770dc2e000a88", features = ["llvm10-0"] }
